name: deploy project
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: install dependencies
        run: npm install

      - name: run unit tests
        run: npm run test --e CI=true
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build the production artifact
        run: npm run build
